---
- name: Install RPM packages
  ansible.builtin.dnf:
    name:
      - git-core
  become: true

- name: Install pre-commit
  ansible.builtin.pip:
    name:
      - pre-commit # https://bugzilla.redhat.com/show_bug.cgi?id=2032554

- name: Run pre-commit
  ansible.builtin.command: pre-commit run --all-files --hook-stage manual --verbose
  args:
    chdir: "{{ zuul.project.src_dir }}"
  register: pc_result
  changed_when: "pc_result.rc == 1"
