---
- name: Set linter failure to false
  ansible.builtin.set_fact:
    linter_failure: false

- name: Include linter tasks
  ansible.builtin.include_tasks: "lint_{{ item }}.yaml"
  loop: "{{ linters }}"

- name: Fail if one linter failed
  ansible.builtin.fail:
    msg: "One or more file(s) failed lint checks"
  when: linter_failure
