---
- name: Install packages
  ansible.builtin.dnf:
    name:
      - git-core
      - python36
      - python37
      - python38
      - pre-commit
  become: true

- name: Run pre-commit
  ansible.builtin.command: pre-commit run --all-files --hook-stage manual --verbose
  args:
    chdir: "{{ zuul.project.src_dir }}"
  register: pc_result
  changed_when: "pc_result.rc == 1"
