---
- name: Install epel-release
  ansible.builtin.package:
    name:
      - epel-release
  become: true

- name: Setup Docker CE repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
  become: true

- name: Install Docker CE
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - centos-release-openshift-origin
    state: present
  become: true

- name: Install Openshift Origin
  ansible.builtin.package:
    name:
      - origin
    state: present
  become: true

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
  become: true

- name: Add OpenShift insecure registry into docker deamon config
  ansible.builtin.lineinfile:
    path: /etc/docker/daemon.json
    regexp: insecure-registries
    line: |
      {"insecure-registries" : [ "172.30.0.0/16" ]}
    create: true
    mode: 0644
  become: true

- name: Make sure docker is running
  ansible.builtin.systemd:
    name: docker
    state: started
  become: true

- name: Start Openshift cluster
  ansible.builtin.command: oc cluster up --base-dir=/tmp --enable="-centos-imagestreams,-sample-templates,persistent-volumes,registry,router,-web-console"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    DOCKER_CONFIG: "/etc/docker/daemon.json"
  become: true
  changed_when: true
